 "use client";

 import { MapPin, Mail, Phone } from "lucide-react";
 import { useState } from "react";
 import { contactFields, contactInfo, contactSubjects } from "@/lib/data/page-data";

 const card = "rounded-card-lg border border-line bg-white";
 
 export default function Page() {
     const [sent, setSent] = useState(false);
	const contactIcons = [Mail, Phone, MapPin];
	return <main className="container flex flex-col gap-8 py-10">
		 <header className="mx-auto max-w-225 px-4 text-center"><span className="text-xs font-bold uppercase tracking-[1.4px] text-brand">Get in touch</span><h1 className="mt-3 font-newsreader text-[clamp(34px,5vw,52px)] font-semibold leading-[1.1]">Let&apos;s talk</h1><p className="mx-auto mt-4 max-w-150 text-base leading-[1.6] text-ink-2">Questions, pitches, partnerships or feedback — we read everything and reply within one business day.</p></header>
		<section className="grid gap-8 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)] xl:gap-10"><form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className={`${card} p-6 md:p-8`}><div className="grid gap-4 sm:grid-cols-2">{contactFields.map(({ label, placeholder, type }) => <label key={label} className="flex flex-col gap-2 text-[13px] font-bold"><span>{label}</span><input required type={type} placeholder={placeholder} className="rounded-input border border-line-2 bg-[#FBFAF7] px-3.5 py-3 text-sm font-normal outline-none focus:border-brand focus:bg-white" /></label>)}</div><label className="mt-4 flex flex-col gap-2 text-[13px] font-bold"><span>Subject</span><select className="rounded-input border border-line-2 bg-[#FBFAF7] px-3.5 py-3 text-sm font-normal">{contactSubjects.map((subject) => <option key={subject}>{subject}</option>)}</select></label><label className="mt-4 flex flex-col gap-2 text-[13px] font-bold"><span>Message</span><textarea required rows={5} placeholder="How can we help?" className="resize-y rounded-input border border-line-2 bg-[#FBFAF7] px-3.5 py-3 text-sm font-normal leading-[1.55] outline-none focus:border-brand focus:bg-white" /></label><button className="mt-5 w-full rounded-btn bg-ink px-4 py-3.5 text-sm font-bold text-white hover:bg-brand">{sent ? "Message sent ✓" : "Send message"}</button></form><div className="flex flex-col gap-4">{contactInfo.map((info, index) => { const Icon = contactIcons[index]; return <div key={info.title} className={`${card} flex gap-4 p-5`}><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-input bg-brand-tint text-brand"><Icon size={19} /></span><div><h2 className="text-[15px] font-bold">{info.title}</h2><p className="mt-1 text-sm leading-[1.5] text-ink-2">{info.first}<br />{info.second}</p></div></div>; })}<div className="rounded-card-lg bg-ink p-5 text-white"><h2 className="font-newsreader text-lg font-semibold">Follow along</h2><p className="mt-1.5 text-[13.5px] text-ink-4">The fastest way to reach us is on social.</p><div className="mt-3.5 flex gap-2"><span className="rounded-input border border-line-dark bg-surface-dark-2 px-3 py-2 text-xs">X</span><span className="rounded-input border border-line-dark bg-surface-dark-2 px-3 py-2 text-xs">in</span><span className="rounded-input border border-line-dark bg-surface-dark-2 px-3 py-2 text-xs">ig</span></div></div></div></section>
		 <section className="flex h-75 items-center justify-center rounded-card-lg border border-line bg-[#E8E6DF]"><div className="text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-brand text-white shadow-lg"><MapPin size={22} /></span><p className="mt-3 text-sm font-semibold text-ink-2">Level 7, Tech Park · Dhaka 1212, Bangladesh</p></div></section>
	 </main>;
 }